services:
  # Service pour l'application Node.js
  app:
    build: .
    ports:
      - "7200:7200"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    depends_on:
      db:
        condition: service_healthy
    # Attend que la base de données soit prête avant de démarrer l'application
    restart: unless-stopped

  # Service pour la base de données MySQL
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      # Persiste les données de la base de données
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  # Volume pour persister les données MySQL
  db_data: